name: 'Deploy via ACI'
description: 'Deploy zip artifact to App Service via ACI'

inputs:
  # app-service-name:
  #   description: 'Name of the deployment target Azure App Service'
  #   required: true
  github-run-id:
    description: 'GitHub Run ID for uniqueness'
    required: true
  environment:
    description: 'Target environment (dev, test, stage, prod)'
    required: true
  resource-group:
    description: 'Resource group for the deployment'
    required: true
  identity-resource-id:
    description: 'Resource ID (mamanged identity id) for ACI'
    required: true
  aci-vnet: 
    description: 'VNET for ACI deployment'
    required: true
  aci-subnet:
    description: 'Subnet for ACI deployment'
    required: true
  client-id:
    description: 'caller client-id'
    required: true
  tenant-id:
    description: 'caller tenant-id'
    required: true
  subscription-id:
    description: 'caller subscription-id'
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure Login with OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}

    - name: Create temporary storage account & container
      shell: bash
      run: |
        # Generate a unique storage account name (lowercase, alphanumeric)
        # STORAGE_ACCOUNT="stgtmp${{ inputs.github-run-id }}$RANDOM"
        # STORAGE_ACCOUNT=$(echo $STORAGE_ACCOUNT | tr '[:upper:]' '[:lower:]')
        # echo "STORAGE_ACCOUNT=$STORAGE_ACCOUNT" >> $GITHUB_ENV
        STORAGE_ACCOUNT="stgtmp${{ inputs.github-run-id }}$(openssl rand -hex 3 | tr -dc 'a-z0-9')"
        STORAGE_ACCOUNT=$(echo "$STORAGE_ACCOUNT" | tr '[:upper:]' '[:lower:]' | cut -c 1-24)  # Storage account names must be 3-24 chars
        echo "STORAGE_ACCOUNT=$STORAGE_ACCOUNT" >> $GITHUB_ENV

        az storage account create \
          --name $STORAGE_ACCOUNT \
          --resource-group ${{ inputs.resource-group }} \
          --location $REGION \
          --sku Standard_LRS \
          --kind StorageV2

        CONNECTION_STRING=$(az storage account show-connection-string --name $STORAGE_ACCOUNT --resource-group ${{ inputs.resource-group }} --query connectionString -o tsv)

        az storage container create --name deploy --connection-string "$CONNECTION_STRING"

        az storage blob upload \
          --connection-string "$CONNECTION_STRING" \
          --container-name deploy \
          --file ./artifact/${ZIP_NAME} \
          --name ${ZIP_NAME}

        SAS_TOKEN=$(az storage blob generate-sas \
          --account-name $STORAGE_ACCOUNT \
          --container-name deploy \
          --name ${ZIP_NAME} \
          --permissions r \
          --expiry $(date -u -d "1 hour" '+%Y-%m-%dT%H:%MZ') \
          --output tsv)

        echo "ZIP_URL=https://${STORAGE_ACCOUNT}.blob.core.windows.net/deploy/${ZIP_NAME}?${SAS_TOKEN}" >> $GITHUB_ENV

    - name: Deploy via ACI
      shell: bash
      env:
        REGION: 'eastus2'
        ACI_MEMORY: 2
        ACI_CPU: 1
        CONTAINER_IMAGE: 'mcr.microsoft.com/azure-cli:latest'
      run: |
        ACI_NAME=aci-${{ inputs.github-run-id }}

        az container create \
          --resource-group ${{ inputs.resource-group }} \
          --name $ACI_NAME \
          --os-type Linux \
          --image $CONTAINER_IMAGE \
          --vnet ${{ inputs.aci-vnet }} \
          --subnet ${{ inputs.aci-subnet }} \
          --cpu $ACI_CPU \
          --memory $ACI_MEMORY \
          --location $REGION \
          --restart-policy Never \
          --assign-identity ${{ inputs.identity-resource-id }} \
          --command-line "/bin/bash -c 'set -x && az login --identity && curl -sSL \"$ZIP_URL\" -o \"$ZIP_NAME\" && az webapp deploy --resource-group \"${{ inputs.resource-group }}\" --name \"${{ inputs.app-service-name }}\" --src-path \"$ZIP_NAME\" --type zip --restart true'"

        for i in {1..30}; do
          STATUS=$(az container show \
            --resource-group ${{ inputs.resource-group }} \
            --name $ACI_NAME \
            --query "instanceView.state" \
            --output tsv)

          echo "Status: $STATUS"

          if [[ "$STATUS" == "Succeeded" ]]; then
            echo "Deployment completed successfully"
            break
          elif [[ "$STATUS" == "Failed" || "$STATUS" == "Stopped" ]]; then
            echo "Deployment failed. Logs:"
            az container logs --resource-group "${{ inputs.resource-group }}" --name "$ACI_NAME"
            exit 1
          fi

          sleep 10
        done

        echo "Final container logs:"
        az container logs --resource-group $${{ inputs.resource-group }} --name $ACI_NAME

        if [[ "$STATUS" != "Succeeded" ]]; then
          echo "Timeout reached - deployment did not complete"
          exit 1
        fi

        az container delete \
          --resource-group $${{ inputs.resource-group }} \
          --name $ACI_NAME \
          --yes || echo "ACI cleanup failed"

        az storage account delete \
          --name $STORAGE_ACCOUNT \
          --resource-group $${{ inputs.resource-group }} \
          --yes || echo "Storage account cleanup failed"
