@baseurl=https://localhost:44318

GET {{baseurl}}/api/v1/todoitems?pageSize=10&pageIndex=1

###

POST {{baseurl}}/api/v1/todoitems
Content-Type: application/json

{
  "name": "a2sdf3",
  "status": 1,
  "secureRandom": "secrand",
  "secureDeterministic": "secdet"
}

###

GET {{baseurl}}/api/v1/todoitems/215e60cf-3db0-488f-a9ec-3ff15cac12d6

###

PUT {{baseurl}}/api/v1/todoitems/d0484e69-484a-48e3-85ae-3ae05f0ea94b
Content-Type: application/json
{
  "name": "a5555588",
  "status": 1,
  "secureRandom": "secrand5588",
  "secureDeterministic": "secdet5588"
}

###

DELETE {{baseurl}}/api/v1/todoitems/d0484e69-484a-48e3-85ae-3ae05f0ea94b

