name: Build SampleApp.Api

on:
  # workflow_run:
  #   workflows: ["Pre-build-deploy-tests"]
  #   types:
  #     - completed
  #   branches:
  #     - main

  # push:
  #   branches:
  #     - main

  workflow_dispatch:
    # inputs:
    #   environment:
    #     type: choice
    #     description: Select environment
    #     required: true
    #     options:
    #       - dev
    #       - prod

env:
  DOTNET_VERSION: '9.x'

jobs:
  build:
    # Only run if the upstream workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || 'dev' }}  # Default to dev if not specified
    outputs:
      build-run-id: ${{ steps.upload-artifact.outputs.run-id }}
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore 
        run: dotnet restore ./SampleApp.Api/SampleApp.Api.csproj

      - name: Publish (includes build)
        run: dotnet publish ./SampleApp.Api/SampleApp.Api.csproj -c Release -o publish --no-restore

      - name: Zip published output 
        run: |
          cd publish
          zip -r ../artifact.zip .

      #default stored for 90 days in GitHub Actions artifact storage
      - name: Upload artifact (only if tests passed)
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.zip
          