# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy SampleApp.UI

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        options:
          - dev
          - prod

env:
  DOTNET_VERSION: '9.x'
  AZURE_STATIC_WEBAPP_NAME: 'blazorui-sampleapp-dev1'
  AZURE_RESOURCE_GROUP: 'rg-dev1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./SampleApp.UI1/SampleApp.UI1.csproj

      - name: Build
        run: dotnet build ./SampleApp.UI1/SampleApp.UI1.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./SampleApp.UI1/SampleApp.UI1.csproj -c Release -o publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: sampleappui1-artifact
          path: publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
      # name: ${{ github.event.inputs.environment }}
      # url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: sampleappui1-artifact
          path: site
 
      - name: debug
        run: |
          echo "deployment token = ${{ secrets.DEPLOYMENT_TOKEN }}"
          echo "environment=${{ github.event.inputs.environment }}"
      
      # - name: List contents of site folder
      #   run: ls -R site

      #not needed until static web app deployments support OIDC
      # - name: Azure Login (OIDC)
      #   uses: azure/login@v2
      #   with:
      #   # These are created manually in Github repo secrets (manual EntraID appreg for deployment with OIDC federated credentials))
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      #deployment_action: upload
      #does not yet support federated OIDC credentials
      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 'b743bc83e0d3f240a90f675aaa0bdc43a4b29d895d385812a17d136bfeaffff706-6e516091-f0eb-4c2d-8571-9d422983d58100f0014066c9ac0f'
          app_location: site
          app_artifact_location: "site/wwwroot"
          api_location: ""  # Leave blank if you don’t have an API
          
          