# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy SampleApp.Api to Azure Web App - api-sampleapp-dev1

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'

env:
  DOTNET_VERSION: '9.x'
  AZURE_WEBAPP_NAME: 'api-sampleapp-dev1'
  AZURE_RESOURCE_GROUP: 'rg-dev1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./SampleApp.Api/SampleApp.Api.csproj

      - name: Build
        run: dotnet build ./SampleApp.Api/SampleApp.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./SampleApp.Api/SampleApp.Api.csproj -c Release -o publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: sampleapp-artifact
          path: publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: sampleapp-artifact
          path: .

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Deploy to Azure Web App
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     slot-name: 'Production'
      #     package: .
      - name: Deploy using temporary Azure Container Instance
        shell: bash
        run: |
          set +e # Don’t exit on error to allow cleanup

          containerName=deploy-temp-container

          echo "Creating container to deploy package..."

          az container create \
            --name $containerName \
            --os-type Linux
            --image mcr.microsoft.com/dotnet/aspnet:9.0 \
            --resource-group $AZURE_RESOURCE_GROUP \
            --vnet vnet-dev1 \
            --subnet subnet-aci-dev1 \
            --environment-variables AZURE_WEBAPP_NAME=$AZURE_WEBAPP_NAME AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP \
            --command-line "bash -c 'apt-get update && apt-get install -y curl gnupg ca-certificates lsb-release apt-transport-https && curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && curl -sSL https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-9.0.100-linux-x64-binaries && dotnet --version && az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src /workspace/sampleapp-artifact.zip'"


          # Wait until the container finishes running
          az container wait --name $containerName --resource-group $AZURE_RESOURCE_GROUP --custom "containerInstance.instanceView.state=='Terminated'"

          echo "Cleaning up container..."
          az container delete --name $containerName --resource-group $AZURE_RESOURCE_GROUP --yes

      - name: Clean up ACI container
        if: failure() || success() # Ensure cleanup happens whether the previous step fails or succeeds
        run: |
          echo "Cleaning up ACI container..."
          az container delete --name deploy-container --resource-group rg-dev1 --yes