name: Deploy SampleApp.Gateway to ACA

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag (e.g., latest or commit SHA)"
        required: true
        default: latest

  workflow_run:
    workflows: ["Build and Push SampleApp.Gateway Container"]
    types:
      - completed

env:
  #RESOURCE_GROUP: rg-dev1
  #ACA_ENVIRONMENT: aspire-env-dev
  #CONTAINERAPP_NAME: sampleapp-gateway
  IMAGE_NAME: sampleapp-gateway
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev #Github env vars
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: Log in to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Use GitHub token instead of PAT for authentication
      - name: Login to GitHub Container Registry with GITHUB_TOKEN
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Test image pull with GitHub token
        run: |
          TAG="${{ github.event.inputs.tag || github.sha }}"
          echo "Testing image pull with GitHub token: ghcr.io/$OWNER/$IMAGE_NAME:$TAG"
          docker pull "ghcr.io/$OWNER/$IMAGE_NAME:$TAG" || echo "Image pull failed but continuing workflow"

      # Update container app to use managed identity with Workload Identity Federation
      - name: Update container app to use GitHub Workload Identity
        run: |
          echo "Updating container app to use workload identity..."
          
          # First, create a system-assigned managed identity for the container app if it doesn't exist
          az containerapp identity assign \
            --name ${{ vars.ACA_CONTAINERAPP_NAME_GATEWAY }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --system-assigned || echo "Managed identity already assigned"
          
          # Get the containerapp's principal ID
          PRINCIPAL_ID=$(az containerapp identity show \
            --name ${{ vars.ACA_CONTAINERAPP_NAME_GATEWAY }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --query principalId -o tsv)
          
          echo "Container App Principal ID: $PRINCIPAL_ID"
          
          # Set up registry with GitHub token
          az containerapp registry set \
            --name ${{ vars.ACA_CONTAINERAPP_NAME_GATEWAY }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --server ghcr.io \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }}
          
          echo "Waiting for registry configuration to propagate..."
          sleep 30

      - name: Verify registry configuration
        run: |
          echo "Verifying registry configuration..."
          az containerapp registry list \
            --name ${{ vars.ACA_CONTAINERAPP_NAME_GATEWAY }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --output json

      - name: Deploy to Azure Container App
        run: |
          TAG="${{ github.event.inputs.tag || github.sha }}"
          echo "Deploying with tag: $TAG"
          
          az containerapp update \
            --name ${{ vars.ACA_CONTAINERAPP_NAME_GATEWAY }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --image "ghcr.io/$OWNER/$IMAGE_NAME:$TAG" \
            --set-env-vars "ASPNETCORE_URLS=http://+:8080" \
            --query properties.configuration.ingress.fqdn