name: Deploy SampleApp.Api to ACA

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag (e.g., latest or commit SHA)"
        required: true
        default: latest

  workflow_run:
    workflows: ["Build and Push SampleApp.Api Container"]
    types:
      - completed

env:
  #RESOURCE_GROUP: rg-dev1
  #ACA_ENVIRONMENT: aspire-env-dev
  #CONTAINERAPP_NAME: api
  IMAGE_NAME: sampleapp-api
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev #Github env vars
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: Log in to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ vars.ACA_CONTAINERAPP_NAME_GATEWAY }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --image $REGISTRY/$OWNER/$IMAGE_NAME:${{ github.event.inputs.tag || github.sha }} \
            --query properties.configuration.ingress.fqdn
