name: Build SampleApp.UI

on:
  workflow_run:
    workflows: ["Pre-build-deploy-tests"]
    types:
      - completed

  # push:
  #   branches:
  #     - main

  workflow_dispatch:
    # inputs:
    #   environment:
    #     type: choice
    #     description: Select environment
    #     required: true
    #     options:
    #       - dev
    #       - prod

env:
  DOTNET_VERSION: '9.x'

jobs:
  build:
    # Enhanced condition to handle edge cases
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && 
       github.event.workflow_run.conclusion == 'success' && 
       github.event.workflow_run.conclusion != 'cancelled')

    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || 'dev' }}  # Default to dev if not specified
    outputs:
      build-run-id: ${{ steps.upload-artifact.outputs.run-id }}
    permissions:
      contents: read

    steps:
      - name: Debug workflow run event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow run status: ${{ github.event.workflow_run.status }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ./SampleApp.UI1/SampleApp.UI1.csproj

      - name: Publish (includes build)
        run: dotnet publish ./SampleApp.UI1/SampleApp.UI1.csproj -c Release -o publish --no-restore

      - name: Copy appsettings.json after publish
        run: cp ./SampleApp.UI1/wwwroot/appsettings.json publish/wwwroot/appsettings.json

      - name: Zip published wwwroot
        run: |
          cd publish/wwwroot
          zip -r ../../artifact.zip .
          cd ../..

      #default stored for 90 days in GitHub Actions artifact storage
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.zip