# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy SampleApp.UI

on:
  workflow_run:
    workflows: ["Build SampleApp.UI"]
    types:
      - completed

  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       type: choice
  #       description: Select environment
  #       required: true
  #       options:
  #         - dev
  #         - prod

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: debug
        run: |
          echo "github.event.workflow_run.id = ${{ github.event.workflow_run.id }}" 
          echo "github.repository = ${{ github.repository }}"
          echo "secrets.GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN }}"
          echo "github.event.inputs.environment = ${{ github.event.inputs.environment }}"
          echo "steps.deploy-to-webapp.outputs.webapp-url = ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          echo "vars.APP_SERVICE_NAME_GATEWAY = ${{ vars.APP_SERVICE_NAME_GATEWAY }}"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for the current repo

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
        # These are created manually in Github repo secrets (manual EntraID appreg for deployment with OIDC federated credentials))
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.APP_SERVICE_NAME_UI }}
          package: artifact.zip

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for the current repo

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
        # These are created manually in Github repo secrets (manual EntraID appreg for deployment with OIDC federated credentials))
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.APP_SERVICE_NAME_UI }}
          slot-name: 'Production'
          package: ./artifact
