# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy SampleApp.UI

on:
  workflow_run:
    workflows: ["Build SampleApp.UI"]
    types:
      - completed

  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       type: choice
  #       description: Select environment
  #       required: true
  #       options:
  #         - dev
  #         - prod

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: debug
        run: |
          echo "github.event.workflow_run.id = ${{ github.event.workflow_run.id }}" 
          echo "github.repository = ${{ github.repository }}"
          echo "secrets.GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN }}"
          echo "github.event.inputs.environment = ${{ github.event.inputs.environment }}"
          echo "steps.deploy-to-webapp.outputs.webapp-url = ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          echo "vars.APP_SERVICE_NAME_GATEWAY = ${{ vars.APP_SERVICE_NAME_GATEWAY }}"

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
        # These are created manually in Github repo secrets (manual EntraID appreg for deployment with OIDC federated credentials))
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for the current repo - GitHub OIDC

      - name: List .zip contents for debug
        run: unzip -l ./artifact/artifact.zip

      - name: Extract artifact.zip
        run: |
          mkdir deploy
          unzip ./artifact/artifact.zip -d deploy

      - name: Replace appsettings.json placeholders
        env:
          CLIENTID: ${{ vars.SETTINGS_AZUREB2C_CLIENTID }}
          BASEURL: ${{ vars.SETTINGS_GATEWAY_BASEURL }}
          SCOPE1: ${{ vars.SETTINGS_GATEWAY_SCOPE1 }}
        run: |
          sed -i "s|__SETTINGS_AZUREB2C_CLIENTID__|$CLIENTID|g" ./deploy/appsettings.json
          sed -i "s|__SETTINGS_GATEWAY_BASEURL__|$BASEURL|g" ./deploy/appsettings.json
          sed -i "s|__SETTINGS_GATEWAY_SCOPE1__|$SCOPE1|g" ./deploy/appsettings.json

      #debug
      - name: Show output substituted config
        run: cat ./deploy/appsettings.json

      - name: List contents of deploy folder for debug
        run: |
          echo "Listing files in ./deploy:"
          ls -R ./deploy

      #Azure static web apps hosting (using static webap deployment token)
      #https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=identity&pivots=github-actions#build-and-deploy
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: \"${{ secrets.UI_STATICWEBAPP_DEPLOYMENT_TOKEN }}\"
          action: "upload"
          skip_app_build: true
          app_location: "./deploy"  # Ensure this points to the folder containing the static files


      #Azure blob storage hosting
      # - name: Upload to Azure Storage (using OIDC)
      #   run: |
      #     az storage blob upload-batch \
      #       --account-name ${{ vars.UI_HOST_STORAGE_ACCOUNT_NAME }} \
      #       --destination \$web \
      #       --source ./deploy \
      #       --overwrite \
      #       --auth-mode login
      #       #--only-show-errors


  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for the current repo

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
        # These are created manually in Github repo secrets (manual EntraID appreg for deployment with OIDC federated credentials))
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      #Azure blob storage hosting
      - name: Upload to Azure Storage (using OIDC)
        run: |
          az storage blob upload-batch \
            --account-name ${{ vars.UI_HOST_STORAGE_ACCOUNT_NAME }} \
            --destination \$web \
            --source ./deploy \
            --overwrite \
            --auth-mode login
