# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy SampleApp.Gateway

on:
  workflow_run:
    workflows: ["Build SampleApp.Gateway"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        options:
          - dev
          - prod

# env:
#   DOTNET_VERSION: '9.x'
#   AZURE_WEBAPP_NAME: 'api-gateway-dev1'
#   AZURE_RESOURCE_GROUP: 'rg-dev1'

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: ${{ env.DOTNET_VERSION }}

  #     - name: Restore dependencies
  #       run: dotnet restore ./SampleApp.Gateway/SampleApp.Gateway.csproj

  #     - name: Build
  #       run: dotnet build ./SampleApp.Gateway/SampleApp.Gateway.csproj --configuration Release --no-restore

  #     - name: Publish
  #       run: dotnet publish ./SampleApp.Gateway/SampleApp.Gateway.csproj -c Release -o publish

  #     - name: Upload build artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: sampleappgateway-artifact
  #         path: publish

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: sampleappgateway-artifact
          path: publish

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
        # These are created manually in Github repo secrets (manual EntraID appreg for deployment with OIDC federated credentials))
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        # These are created automatically when creating Azure App Service and specifying the repo - integration
        #   client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_78EDC076F62A4BDE95214A4FE559C46A }}
        #   tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_02767756C0BD402DABA351F3EDC94DF9 }}
        #   subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DEFCA863CA1D40F0A851534635EACA7F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: .

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact #The deploy script downloads the artifact from the specific triggering build run — not "the latest" in general.
        uses: actions/download-artifact@v4
        with:
          name: sampleappgateway-artifact
          path: publish

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
        # These are created manually in Github repo secrets (manual EntraID appreg for deployment with OIDC federated credentials))
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.APP_SERVICE_NAME_GATEWAY }}
          slot-name: 'Production'
          package: .
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read #This is required for actions/checkout

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up .NET Core
#         uses: actions/setup-dotnet@v4
#         with:
#           dotnet-version: '9.x'

#       - name: Build with dotnet
#         run: dotnet build SampleApp.Gateway/SampleApp.Gateway.csproj --configuration Release

#       - name: dotnet publish
#         run: dotnet publish SampleApp.Gateway/SampleApp.Gateway.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: .net-app
#           path: ${{env.DOTNET_ROOT}}/myapp

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#     permissions:
#       id-token: write #This is required for requesting the JWT
#       contents: read #This is required for actions/checkout

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: .net-app
      
#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_78EDC076F62A4BDE95214A4FE559C46A }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_02767756C0BD402DABA351F3EDC94DF9 }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DEFCA863CA1D40F0A851534635EACA7F }}

#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'api-gateway-dev1'
#           slot-name: 'Production'
#           package: .
          
