name: Deploy SampleApp.Gateway to ACA

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag (e.g., latest or commit SHA)"
        required: true
        default: latest

  workflow_run:
    workflows: ["Build and Push SampleApp.Gateway Container"]
    types:
      - completed

env:
  #RESOURCE_GROUP: rg-dev1
  #ACA_ENVIRONMENT: aspire-env-dev
  #CONTAINERAPP_NAME: sampleapp-gateway
  IMAGE_NAME: sampleapp-gateway
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev #Github env vars
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: Log in to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Test if we can pull the image with the PAT
      - name: Test PAT by logging into GHCR
        run: |
          echo "${{ secrets.PAT_ACA_PULL_GHCR_PRIVATE_IMAGE }}" | docker login ghcr.io -u $OWNER --password-stdin
          echo "Docker login successful, testing image pull..."
          docker pull ghcr.io/$OWNER/$IMAGE_NAME:${{ github.event.inputs.tag || github.sha }} || echo "Image pull failed but continuing workflow"

      # Remove existing registry configuration
      - name: Remove existing registry configuration
        run: |
          echo "Removing existing registry configuration..."
          az containerapp registry remove \
            --name ${{ vars.ACA_CONTAINERAPP_NAME_GATEWAY }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --server ghcr.io || echo "No registry to remove or removal failed"
      
      # Set registry with explicit wait
      - name: Set GHCR registry on container app (private image auth)
        run: |
          echo "Setting new registry authentication..."
          az containerapp registry set \
            --name ${{ vars.ACA_CONTAINERAPP_NAME_GATEWAY }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --server ghcr.io \
            --username $OWNER \
            --password "${{ secrets.PAT_ACA_PULL_GHCR_PRIVATE_IMAGE }}"
          
          echo "Waiting for registry configuration to propagate..."
          sleep 30
      
      - name: Verify registry configuration
        run: |
          echo "Verifying registry configuration..."
          az containerapp registry list \
            --name ${{ vars.ACA_CONTAINERAPP_NAME_GATEWAY }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --output json

      - name: Deploy to Azure Container App
        run: |
          TAG="${{ github.event.inputs.tag || github.sha }}"
          echo "Deploying with tag: $TAG"
          
          # Force image pull with explicit credentials
          az containerapp update \
            --name ${{ vars.ACA_CONTAINERAPP_NAME_GATEWAY }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --image "ghcr.io/$OWNER/$IMAGE_NAME:$TAG" \
            --set-env-vars "ASPNETCORE_URLS=http://+:8080" \
            --query properties.configuration.ingress.fqdn