name: Build SampleApp.Api

on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:
    # inputs:
    #   environment:
    #     type: choice
    #     description: Select environment
    #     required: true
    #     options:
    #       - dev
    #       - prod

permissions:
  id-token: write
  contents: read

env:
  DOTNET_VERSION: '9.x'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-run-id: ${{ steps.upload-artifact.outputs.run-id }}
    environment:
      name: ${{ github.event.inputs.environment }}  #
    steps:
      - name: Checkout repo for build
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      #build full solution including test projects
      - name: Restore & Build
        run: |
          dotnet restore ./SampleApp.Api/SampleApp.Api.csproj
          dotnet build ./SampleApp.Api/SampleApp.Api.csproj --configuration Release --no-restore

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Run unit tests
        id: unit-tests-step
        run: dotnet test ./Test.Unit/Test.Unit.csproj --logger "trx;LogFileName=unit_results.trx" --no-build --no-restore

      - name: Generate HTML report
        run: |
          reportgenerator \
            -reports:./Test.Unit/TestResults/unit_results.trx \
            -targetdir:./Test.Unit/TestResults/report \
            -reporttypes:Html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: test-results-html
          path: ./Test.Unit/TestResults/report

      - name: Publish (only if tests passed)
        if: steps.unit-tests-step.outcome == 'success'
        run: dotnet publish ./SampleApp.Api/SampleApp.Api.csproj -c Release -o publish --no-build

      - name: Zip published output (only if tests passed)
        if: steps.unit-tests-step.outcome == 'success'
        run: zip -r artifact.zip publish

        #default stored for 90 days in GitHub Actions artifact storage
      - name: Upload artifact (only if tests passed)
        if: steps.unit-tests-step.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.zip
          